server:
  port: 8081

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 3000
          max-retries: 3
          multiplier: 2.0

  jackson:
    deserialization:
      use-big-decimal-for-floats: true

logging:
  level:
    com.orderpipeline: DEBUG
